# Generated by Django 5.1.4 on 2025-03-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mssv', models.CharField(max_length=10, unique=True)),
                ('ho_ten', models.CharField(max_length=100)),
                ('ngay_sinh', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('so_dien_thoai', models.CharField(blank=True, max_length=10, null=True)),
                ('lop', models.CharField(max_length=50)),
                ('nganh_hoc', models.CharField(max_length=100)),
            ],
        ),
    ]
